Add typesVersions to support node moduleResolution
When importing from a module using moduleResolution:node, the following error would be emitted:

```
error TS2307: Cannot find module 'resumable-stream/ioredis' or its corresponding type declarations.
  There are types at 'node_modules/resumable-stream/dist/ioredis.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

import { createResumableStreamContext } from 'resumable-stream/ioredis';
```